1. Set the variable test1 to the string &#39;This is a test of the emergency text system,&#39; and save test1 to a
file named test.txt.
2. Read the contents of the file test.txt into the variable test2. Is there a difference between test 1
and test 2?
3. Create a CSV file called books.csv by using these lines:
title,author,year
The Weirdstone of Brisingamen,Alan Garner,1960
Perdido Street Station,China Miéville,2000
Thud!,Terry Pratchett,2005
The Spellman Files,Lisa Lutz,2007
Small Gods,Terry Pratchett,1992
4. Use the sqlite3 module to create a SQLite database called books.db, and a table called books with
these fields: title (text), author (text), and year (integer).
5. Read books.csv and insert its data into the book table.
6. Select and print the title column from the book table in alphabetical order.
7. From the book table, select and print all columns in the order of publication.
8. Use the sqlalchemy module to connect to the sqlite3 database books.db that you just made in
exercise 6.
9. Install the Redis server and the Python redis library (pip install redis) on your computer. Create a
Redis hash called test with the fields count (1) and name (&#39;Fester Bestertester&#39;). Print all the fields for
test.
10. Increment the count field of test and print it.

# Answer

1. ```python
test1 = 'This is a test of the emergency text system,'
with open('test.txt', 'w') as file:
    file.write(test1)
```

2. ```python
with open('test.txt', 'r') as file:
    test2 = file.read()
print(test1 == test2) # True
```
There is no difference between test1 and test2 as they contain the same string.

3. ```python
import csv

data = [['title', 'author', 'year'],
        ['The Weirdstone of Brisingamen', 'Alan Garner', 1960],
        ['Perdido Street Station', 'China Miéville', 2000],
        ['Thud!', 'Terry Pratchett', 2005],
        ['The Spellman Files', 'Lisa Lutz', 2007],
        ['Small Gods', 'Terry Pratchett', 1992]]

with open('books.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(data)
```

4. ```python
import sqlite3

conn = sqlite3.connect('books.db')
c = conn.cursor()

c.execute('''CREATE TABLE books
             (title TEXT, author TEXT, year INTEGER)''')

conn.commit()
conn.close()
```

5. ```python
import csv
import sqlite3

conn = sqlite3.connect('books.db')
c = conn.cursor()

with open('books.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        if row[0] != 'title':
            c.execute("INSERT INTO books VALUES (?, ?, ?)", row)

conn.commit()
conn.close()
```

6. ```python
import sqlite3

conn = sqlite3.connect('books.db')
c = conn.cursor()

c.execute("SELECT title FROM books ORDER BY title ASC")
result = c.fetchall()

for row in result:
    print(row[0])

conn.close()
```

7. ```python
import sqlite3

conn = sqlite3.connect('books.db')
c = conn.cursor()

c.execute("SELECT title, author, year FROM books")
result = c.fetchall()

for row in result:
    print(row)

conn.close()
```

8. ```python
from sqlalchemy import create_engine, Table, Column, Integer, String, MetaData

engine = create_engine('sqlite:///books.db', echo=True)
metadata = MetaData()

books = Table('books', metadata,
              Column('title', String),
              Column('author', String),
              Column('year', Integer)
              )

metadata.create_all(engine)
```

9. ```python
import redis

r = redis.Redis(host='localhost', port=6379, db=0)

r.hmset('test', {'count': 1, 'name': 'Fester Bestertester'})

result = r.hgetall('test')
for key, value in result.items():
    print(f'{key}: {value.decode("utf-8")}')
```

10. ```python
count = r.hincrby('test', 'count', 1)
print(count)
```
This will increment the value of the `count` field in the Redis hash `test` by 1 and print the new value of `count`.